### ISSUE TITLE
please work on a docker version

### ISSUE THREAD

**Issue by saeedmsdi** [cloudscribe/cloudscribe.SimpleContent#223]
Hi,

Please work on a docker version too 👍

**Comment by joeaudette** [comment]
Hi,

I do think it would be nice from a marketing point of view to have cloudscribe docker images in docker hub, but it would be a lot of work for me because there are lots of different ways to configure cloudscribe using our project templates, so I would have to make and maintain a lot of different docker images for all the different ways it can be configured. Maybe some day I will do that but not sure I want to get into maintaining all that stuff, it is enough work for me maintaining the code without getting involved in how people deploy their apps. cloudscribe can certainly be deployed in many different hosting environments including docker but there is really nothing cloudscribe specific about that, it is the same for any asp.net core application. Community members could also make docker images and share them on docker hub.

The things is that I don't ship a cloudscribe "app", I only ship nuget packages and project templates so that you can own the main web app and customize it with your own code before deployment. Docker is just a deployment environment and since my intention is that you own the main web application where you can wire up cloudscribe packages in different configurations, then it should be up to you to deploy your application to docker or any other hosting environment.

There are tools available in Visual Studio to help you dockerize your app https://blogs.msdn.microsoft.com/webdev/2016/11/16/new-docker-tools-for-visual-studio/

Microsoft has some more docker documentation here: https://docs.microsoft.com/en-us/aspnet/core/publishing/docker

There is also an article in docker documentation for dotnet core apps here: https://docs.docker.com/engine/examples/dotnetcore/#build-and-run-the-docker-image

**Comment by joeaudette** [comment]
I will investigate and ponder the idea of whether the cloudscribe project template could have options for including docker files. There might be some things we could do there to make it easier for using docker. 

I think the main challenge though is that most people probably would want the database on a different docker image if using MSSQL, MySql, or PostgreSql. So then it gets more complicated and requires multiple docker images and orchestration. 

I am not currently an expert on docker, but I would like to learn more about it and then maybe I will get some ideas.
