### ISSUE TITLE
Is Index view for blog suppose to have noindex?

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe.SimpleContent#298]
Few days ago I submitted sitemap to google and today I got email that "Submitted URL marked ‘noindex’". I checked and sitemap contains link to index blog page and file:
`src\cloudscribe.SimpleContent.CompiledViews.Bootstrap4\Views\Blog\Index.cshtml`
contains:
`<meta name="robots" content="noindex, follow" />`
Is it intended behavior? 
Update: I actually submitted link to blog so perhaps it is why I got that error message from google

**Comment by joeaudette** [comment]
Thanks for the bug report!
It is intended to have no-index on the blog index/post list page, it is not intended to submit the blog index page in the search site map.
This is fixed in the latest nugets.
The reason we don't want google to index the blog post list is because that leads to duplicate content which is bad for seo. We only want them to index the actual post urls.
