### ISSUE TITLE
Create page options with new Templates - suggestion to make this clearer

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#315]
Just doing my first test of this (looking great!), and found myself a little confused by the fact that the two ways of creating the page are styled differently, one being a button the other a link (see below):
![image](https://user-images.githubusercontent.com/10574730/43268418-80f97f16-90e8-11e8-94b9-f9f7ffde984f.png)
For me this would be clearer if the upper one ("New Page …") was also a button.

**Comment by CrispinF** [comment]
Similar here:
![image](https://user-images.githubusercontent.com/10574730/43272234-617f59cc-90f1-11e8-8b2e-903b987611a3.png)

**Comment by joeaudette** [comment]
Originally I had the new page link styled as a button, but I thought it was ugly for some reason and changed it to a link style. I am willing to change it back to a button though.

In general I favor buttons for actions and don't favor button style for links unless the link is a call to action type of thing, hence "view" is a link and restore and delete are buttons.

However, since you sponsored this work and I don't feel strongly about it I'm happy to change to make all these look like buttons.

**Comment by joeaudette** [comment]
I've published updated nuget with changes to style the links as buttons. It may be a few minutes before the updated nuget is available

**Comment by CrispinF** [comment]
Thanks. 
I know what you mean for links that do not alter the state of anything, but it's more pleasing to have consistency within any one context, and no less understandable.

**Comment by joeaudette** [comment]
this is completed in the latest nugets
