### ISSUE TITLE
Why is my new page in the top menu? Home page cannot have child pages?

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#321]
New page created, originally with no Parent Slug. It appeared in top menu - good. Edit the page and set Parent Slug to "home" (also tried "Home"). 
![image](https://user-images.githubusercontent.com/10574730/43308206-b21e0cfc-9178-11e8-85e1-bf6327cd3488.png)

The Page Manager understands this:
![image](https://user-images.githubusercontent.com/10574730/43308224-c4fe39be-9178-11e8-8e58-13b85d2dafc2.png)
(and it's different if I do not make the new page a child of /home:
![image](https://user-images.githubusercontent.com/10574730/43308439-848408ea-9179-11e8-8dd4-b8edc41baff4.png)
)

but the page remains in the top menu instead of being a child page of /home:
![image](https://user-images.githubusercontent.com/10574730/43308240-d6d93166-9178-11e8-9983-d51d876bd0b1.png)

I'm wondering whether all top menu pages are regarded as children of /home, which therefore cannot have child pages in the sense of a sub-menu?

**Comment by joeaudette** [comment]
home is a special page that should not be set as parent page, it is sort of a pseudo parent to other root pages in the way the navigation view markup works but because of that it should not have child explicit child pages because it is the root of the entire site.

You can see in the markup for the cloudscribe.Web.Navigation [Bootstrap4TopNavWithDropdowns.cshtml](https://github.com/cloudscribe/cloudscribe.Web.Navigation/blob/master/src/cloudscribe.Web.Navigation/Views/Shared/Components/Navigation/Bootstrap4TopNavWithDropdowns.cshtml)

that the site root LI aka the home page is rendered first, then other root level pages are rendered, so the home page can never have dropdown items like other root pages.

Trying to change that would open a can of worms where SimpleContent needs different topnav view than other things using the navigation component. In practice I think it is best to not have dropdown pages under home.

**Comment by joeaudette** [comment]
for example in breadcrumbs other root pages are shown with Home > Page
even though they are not explicit child pages.

**Comment by joeaudette** [comment]
to be more clear home is the root of the entire tree and already is the parent of other root nodes, you can see here in the menu logic:

    <ul class="navbar-nav mr-auto" role="menubar">
    <li cwn-data-attributes="@Model.RootNode.Value.DataAttributes" class='@Model.GetClass(Model.RootNode.Value, "nav-item")'><a class="nav-link" href="@Url.Content(Model.AdjustUrl(Model.RootNode))">@Html.Raw(Model.GetIcon(Model.RootNode.Value))@Model.AdjustText(Model.RootNode)</a></li>
    @if (Model.HasVisibleChildren(Model.RootNode))
    {
        @foreach (var node in Model.RootNode.Children)
        {
            if (!Model.ShouldAllowView(node)) { continue; }
            if (!Model.HasVisibleChildren(node))
            {
                <li class='@Model.GetClass(node.Value, "nav-item")' cwn-data-attributes="@node.Value.DataAttributes"><a class="nav-link" href="@Url.Content(Model.AdjustUrl(node))">@Html.Raw(Model.GetIcon(node.Value))@Model.AdjustText(node)</a></li>
            }
            else
            {
                    <li class='@Model.GetClass(node.Value, "nav-item dropdown",  "active", true)' cwn-data-attributes="@node.Value.DataAttributes">
                        <a class="nav-link dropdown-toggle" id="dropdown-@node.Value.Key" aria-haspopup="true" aria-expanded="false" href="@Url.Content(Model.AdjustUrl(node))">@Html.Raw(Model.GetIcon(node.Value))@Model.AdjustText(node) </a>
                        @Model.UpdateTempNode(node) <partial name="Bootstrap4NavigationNodeChildDropdownPartial" model="@Model" />
                </li>
                }
            }
        }
    </ul>

Home is the rootnode and all other root level pages are direct children of home because it is a tree structure. So if home supported dropdowns then there could be no other root level pages.

**Comment by joeaudette** [comment]
maybe I should prevent anyone from setting the root slug as parent slug and automatically remove it if someone does.

**Comment by joeaudette** [comment]
in the latest nugets, if you try to explicitly set the home page as parent slug it will instead be set to empty making a root level page, a warning is logged in order to be helpful if someone doesn't understand the behavior. 

As mentioned above since the menu is a tree structure with the home page as the root of the tree, it is not possible to have dropdown page children on the home page in addition to having other root level pages because all root level pages are direct children of the site root aka home page in the tree structure.

**Comment by CrispinF** [comment]
@joeaudette thanks for clarifying, and your change sounds good.

**Comment by CrispinF** [comment]
@joeaudette tested ok. Using latest, "home" removed as parent slug on saving, and a warning logged. Happy to close this one. Some appropriate words in the SimpleContent documentation might be useful.
