### ISSUE TITLE
Browse server popup - minor layout queries

### ISSUE THREAD

**Issue by StewartBellamy** [cloudscribe/cloudscribe.SimpleContent#325]
I didn't find the select button immediately obvious, my eye was naturally drawn to the bottom right corner of the popup.  Perhaps make it a bootstrap primary button and also duplicate it next to the very obvious delete file button? 

Consider using bootstrap rows or form groups to give some white space between various components, e.g. between crop button / image name / delete file.

![image](https://user-images.githubusercontent.com/10956017/43315250-4681b646-918d-11e8-8d2a-96640b1a1ebe.png)

**Comment by joeaudette** [comment]
in the latest nugets I've added an additional select button under the image preview but kept the top one because the same dialog is used for selecting other kinds of files where the image preview would not be shown and in that case it is more obvious next to the disabled input that shows the selected file path.

**Comment by StewartBellamy** [comment]
Additional select button now appearing next to crop.
