### ISSUE TITLE
Advanced metadata for pages and posts?

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#331]
Anything in the pipeline for managing advanced metadata on pages and posts? You already mentioned implementations of FB and Twitter, which is great, so I'm thinking of other schemes such as Dublin Core where the values are related to page/post content not static for the site. (Noting that some values will want a site default that can be overridden on a page/post).

**Comment by joeaudette** [comment]
Yes actually at the bottom of the main readme for this project in the planned features section I have a line item for "more advanced meta data capabilities"

I have put some thought into this problem previously and came up with an idea for an approach to solve it.

First I will define the problem as "How to enable non technical users to added advanced meta data to the page in a friendly way where they can't break anything"

That definition of the problem rules out letting the user edit raw html meta data that would just get rendered into the page since that could easily break the page or post.

## High level solution

Some kind of model for MetaData will be used and the model will be serialized as json into the MetaJson field, so that it can be deserialized again for editing again. At the same time on saving the page the model would be rendered into html and saved into the MetaHtml field so that when the page is rendered it simply dumps the MetaHtml into the head. The trick is that users cannot directly edit and mess up the MetaHtml field. There needs to be some kind of js editor that can manage the model as json client side and on postback it would be able to update the MetaHtml based on the json and server side model represented by the json. So, the solution has some similarities with how content templates work in so far as both use serialized models. But whereas template models are arbitrary models, meta data needs a standard model of some kind.

And then there are other issues that may be related if meta schemas have to be declared in the html element of the layout etc or if they require xhtml instead of html.

I actually did the easy part some time ago, in that the MetaJson and MetaHtml fields already exist on both page and post. They are just not used yet.

## Remaining work

* Come up with the details of exactly how the meta should be rendered, ie specifics of dublin core or whatever schema or schemas are to be supported.
* Deciding what the model for meta data should look like, some kind of list obviously, depends on the decided schema.
* Implementing some kind of js/html editor for the model to add remove sort metadata items, and how to make a friendly UI for that.

Obviously an understanding of exactly what will be rendered is needed to in order to design the model for meta data, and that entails deciding on exactly what to support, ie is Dublin Core really the right choice, what other alternatives are there and can the same model work for different schemes or do we commit to a specific scheme like Dublin core, etc. 

However, like anything else that is non trivial work, it is not my top priority, paid work and my strategic goals come first unless someone wants to sponsor development effort to make it my top priority.

**Comment by joeaudette** [comment]
As I recall from research some years ago, Dublin core is pretty open ended and therefore a bit complex. I think you can define your own vocabularies etc, which would probably require some back end administrative page just to define and manage the vocabulary, then surfacing that in the UI for editing meta data.

That would also require a user to know and understand the vocabulary.

Given that some meta data is already used in the markup with schema.org, it might be better to stick with that since it has a lot of pre-defined vocabulary. But still it is pretty extensive vocabulary, and how much of it to surface in the UI that average users could really understand is a question. It might be best to select a subset of most commonly used and useful vocabulary form schema.org and target that as a goal.

This could easily become a very complex solution if we try to make it meet all possible needs.

**Comment by joeaudette** [comment]
and of course content templates already could render their own model specific schema.org meta data into the markup of the render view

**Comment by jasongaylord** [comment]
I'm also interested in this @joeaudette. We can probably talk about this more offline. I'm interested in setting the [open graph values](http://ogp.me/#types) for pages and blog posts. I'd like to be able to set site values but allowing overrides on individual pages and blog posts. For example, we may be able to use the blog post title as the title, post teaser as the description, and the first image it finds as the image. Again, just a thought. We'd have to discuss more.

**Comment by joeaudette** [comment]
@jasongaylord have you seen what it currently does for open graph and twitter? It does already extract the first image and set description etc, there are some settings that are page/post specific and some which are used across pages and posts that come from Administration > Content Settings.
you can see [page meta here](https://github.com/cloudscribe/cloudscribe.SimpleContent/blob/master/src/cloudscribe.SimpleContent.CompiledViews.Bootstrap4/Views/Page/MetaPartial.cshtml) and [post meta here](https://github.com/cloudscribe/cloudscribe.SimpleContent/blob/master/src/cloudscribe.SimpleContent.CompiledViews.Bootstrap4/Views/Blog/BlogMetaPartial.cshtml), and note there is also meta data in the content using schema.org syntax.

**Comment by joeaudette** [comment]
note that teaser is html content, it can't really be used in a meta attribute because it contains markup and can be longer than what meta descriptions typically are and it can contain images etc. We specifically have the meta description property which is not supposed to contain markup so it is the right thing to use for meta description.

**Comment by joeaudette** [comment]
I'm feeling less inclined that this will ever get done or really be needed in simplecontent as we already have facebook and twitter meta data covered and we have schema.org meta data in the markup for pages and posts.

Dublin core is a big enterprisy thing that is hard to grok or use correctly and it would be very difficult to implement it in some user friendly way. 

Given the content template feature could be used to make templates with other additional schema.org meta data I'm inclined to close this and remove the labels.

If someone comes along and wants to sponsor the major effort needed this could be re-opened later.
