### ISSUE TITLE
Slug for new post?

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe.SimpleContent#334]
I believe that earlier versions it was possible to provide slug when you create new blog post but now I cannot see it. 
Also it would be nice to have ability to edit slug when I do edit post. Sometimes I forgot to set slug and system did auto generate slug and then it is really painful to change.

**Comment by joeaudette** [comment]
as far as I know slugs for posts and pages are always auto generated from the title if they are empty. You can edit page slugs but blog post slugs have never been in the edit page Ui that I know of, it just uses a hidden field and since it will be empty for new posts it would be auto generated.

However it always occurred to me that some people might want to edit post slugs so I put the input in a separate partial view so you could copy that view local and make it a visible input instead of a hidden field.
https://github.com/cloudscribe/cloudscribe.SimpleContent/blob/master/src/cloudscribe.SimpleContent.CompiledViews.Bootstrap4/Views/Blog/EditSlugPartial.cshtml

**Comment by cheverdyukv** [comment]
Hi Joe.

Thank you for that info. But is there any reason why it cannot be always visible? And is there anything for create? Right now I'm using Open Live Writer and I use it only because it allows to specify slug so Id of that post and slug are created from slug I provided. One of my blogs uses non English language and I prefer to keep Id and slug in English.

**Comment by joeaudette** [comment]
Overriding that view should work for new posts to be able to specify the slug.

I consider slug is kind of a non user friendly concept, and since 99% of the time it should be just generated by the title I chose not to show it by default on the blog to keep the UX simple. I chose differently for page because it already has a bunch of additional settings in a separate settings tab and it seemed ok to put the slug there where it is out of the way and users don't have to think about it.  Also [urls should not change](https://www.w3.org/Provider/Style/URI) so therefore slugs should not change and inviting users to change it with a highly visible setting invites them to mess up their SEO. So I consider slug an advanced idea that non technical users should not be exposed to by default.

Since blog does not have an extra tab with more settings to add it means it has to go right on the main edit page and is something more the user is forced to think about. I will consider adding it but maybe with a config setting to hide it or not, but really what is so hard about overriding a view if you want that? You can override a view per theme and thus control it per tenant if you want but if I make it a config setting then that is not tenant specific so it is not as good of a solution.

If you use nodb the slug does end up being the id of the post or page but of course it would be problematic to change the id after it is created so that does not happen.
When using a database a guid id is always used no matter what live writer does.

**Comment by cheverdyukv** [comment]
Hi Joe

Thanks for great explanation. I agree that slug is technical details and most users should not worry about it.
Could you please explain or point to page how can I overwrite view per theme?

**Comment by cheverdyukv** [comment]
It works great! Thank you!
