### ISSUE TITLE
A lot of errors about teaser truncation producing invalid html

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe.SimpleContent#336]
![image](https://user-images.githubusercontent.com/18220536/44302347-881dec00-a2db-11e8-8ff0-01827031dd5e.png)
I would assume that message should be displayed only once? Right now I have 105 pages of errors in syslog and most of them is about teaser truncation.

**Comment by joeaudette** [comment]
that truncation doesn't always produce valid markup so it tests it and retries until it gets valid markup and it logs each retry.

Keep in mind that strings are immutable so we don't want to have to keep creating strings in a loop like that and it definitely should log that problem since each created string uses memory.

I suggest when you see those errors it means you should manually create a teaser override for that article since it can't easily auto truncate it without a lot of tries creating strings, or disable the teaser feature and don't use it if you have that happening for lots of articles.

**Comment by cheverdyukv** [comment]
Hi Joe. 

Manually create is not really an option because because it introduces more work for me and it happens quite often. As an idea is it possible to create teaser as plan text? Meaning remove html tag and leave only text and build teaser from that?

And also does it happens every time teaser is displayed or only at creation of post?

**Comment by joeaudette** [comment]
Currently it displays every time the list is rendered. But I think you have a good idea that it should happen at save time only, we should add a new field for the AutoGenTeaser and populate it at save time to avoid the cost of generating it over and over at display time.

I have a lot going on so not sure how soon I can get to this but  I will get to it as soon as  I can.

**Comment by joeaudette** [comment]
This is fixed in the latest nugets, but it will require re-publishing any posts that log the error since the teaser is created on save.

**Comment by cheverdyukv** [comment]
It works now. Thank you!
