### ISSUE TITLE
Images Dump in Root Media Folder

### ISSUE THREAD

**Issue by jasongaylord** [cloudscribe/cloudscribe.SimpleContent#345]
When using Open Live Writer, all of the images uploaded dump in the same folder and overwrite each other. Would be great if we could have a folder structure so we don't run into image naming issues.

**Comment by joeaudette** [comment]
What folder structure and logic do you propose?

As far as I know the images get posted in a separate rpc request with no additional information so nothing to tie it a specific post that may come in in the next request. It is stateless so images are posted and we return the url, which OLW then uses in the body of the post that comes in on a subsequent rpc request.

The only logic I could think of is maybe auto creating folders based on date, but then if you upload image files with the same name on the same day they would still overwrite. We could maybe use guid string for the image names instead of the original file name but that has its down side too, you end up with a big folder full of obscure file names.

I'm open to suggestion if you have a specific suggestion. I think it could also be solved by naming images as you want them before adding them to a post in OLW. I don't know of a way for any mechanism to allow choosing the folder the image lands in on a per image or post basis.

**Comment by jasongaylord** [comment]
@joeaudette I think there's a way to do it. I'm just getting started with cloudscribe and am currently using Orchard. Let me check into it more and I'll post back here.

**Comment by joeaudette** [comment]
@jasongaylord sounds good, you can see the [MetaweblogService](https://github.com/cloudscribe/cloudscribe.SimpleContent/blob/master/src/cloudscribe.SimpleContent.MetaWeblog/MetaWeblogService.cs) which is where any changes would have to be made.

**Comment by jasongaylord** [comment]
@joeaudette My mistake Joe. It appears that the recommendation for this would be to drop images in a folder structure by dates (i.e. images/blog/2018/09/27/picture.jpg). I guess if I'd like that I can always roll my own.

**Comment by joeaudette** [comment]
re-opening this as I think we should have something built in to make that easier.
Not sure how soon I will get to it but I will get to it.

**Comment by jasongaylord** [comment]
Is there a proposed structure? Also, I've started using web images to offload to blog storage. Having a provider to offload files to another storage medium would be awesome (and probably another feature).

**Comment by joeaudette** [comment]
While I was fixing other issue in the metaweblog api I went ahead and changed it so uploaded images go into date folders like /media/images/2018/10/23/someimage.jpg

Is that satisfactory enough to close this?
