### ISSUE TITLE
Compiled Views Not Accessible

### ISSUE THREAD

**Issue by jasongaylord** [cloudscribe/cloudscribe.SimpleContent#351]
I haven't had a chance to fully review yet, but I created a ViewComponent with a compiled view. Without making any configuration changes in SimpleContent, I could not get the view to load. I'm guessing there's something happening in the middleware that does not allow the default views from AspNet to be rendered.

**Comment by jasongaylord** [comment]
If you are looking for an example, check out my cloudscribe.TwitterWidget repo.

**Comment by joeaudette** [comment]
@jasongaylord you should create a sample web app in your repo that consumes the twitter widget with a project reference to test it. I would use our project template to create a cloudscribe web app using NoDb that way the content files can be in source control and then if you can't get it working I can try it and have the same data to see what you see. Really the demo web doesn't even have to be cloudscribe, your twitter project doesn't have any cloudscribe dependencies that I can see so it isn't really cloudscribe specific and probably shouldn't be named cloudscribe since that is my trademark. It looks to me like your widget could/should work in any asp.net core mvc app if properly set up.

There is definitely no middleware blocking it.

If you create a web app in your repo and can't get it working there let me know and I'll pull down the code and have a look.

**Comment by jasongaylord** [comment]
@joeaudette Demo app is done and I've removed the name cloudscribe. It's also removed from the NuGet package. Just thought it would be easier to find components that could be used with the CMS.

**Comment by joeaudette** [comment]
@jasongaylord I'm happy to create a page on cloudscribe.com to list useful things that can be easily integrated, so they don't all have to have cloudscribe in the name especially if they are also useful on their own in general. 

If you really want to brand it as cloudscribe, I'm open to that, could move it to a repo under cloudscribe org and I can add you to the org if you have interest in helping out with cloudscribe longer term. Many of the smaller cloudscribe components are useful separate from the big features of cloudscribe core and simplelcontent, ie the navigation, pagination libraries are more widely used than the big features.

**Comment by joeaudette** [comment]
@jasongaylord I just tested and it worked fine for me.
Steps:

* I created a new cloudscribe project using our project template, I used the default settings with NoDb
* added your nuget package
* added the config with my twitter credentials, kept your username
* added services.AddTwitterWidget(config.GetSection("TwitterOptions"));
* edited /sitefiles/s1/themes/custom1/_Layout.cshtml and added this in the footer area:
   
    @await Component.InvokeAsync("RetrieveTweets", new { })

and then right click the project and view in browser and I see your recent tweets.

**Comment by jasongaylord** [comment]
@joeaudette I would be happy to contribute longer term (as I have time). I started building something just like this but you were further along than I so I switched. :)

I'll try it again in my app.

**Comment by joeaudette** [comment]
@jasongaylord I've invited you to the cloudscribe org. Maybe we could schedule a brief skype call sometime soon just for a get to know each other a little bit and to discuss my goals and plans for cloudscribe?
