### ISSUE TITLE
Allow custom JS on page without a URL

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#359]
It's useful to be able to add a JS URL using the Developer Tools, but it would be nice to be able to store raw JS there, rather than needing server access to publish a separate resource.

In mojoPortal I've used this capability to publish some JSON-LD onto pages to improve their SEO and Linked Data goodness.  (Clearly for a custom data-driven feature this linked data could be auto- generated in server code, but for small sites with HTML pages managed by SimpleContent this would be a great feature).

This relates to the issue about improved metadata #331 but allowing raw script would meet some aspects of this in a powerful way.

**Comment by joeaudette** [comment]
I'm reluctant to agree to have something like that built in. It could be very easily implemented and re-used as a custom content template for those who need something like that and it could be shared as a nuget without being baked in.

## My reasons for reluctance

* Modern browsers support "Content Security Policy" which can be used to block all inline script as a defense against XSS. The modern trend is away from inline scripts for this reason and others. I would rather not have something baked in that by design clashes with Content Security Policy.
* Having something built in that lets that kind of direct access is providing tools that non-technical users can shoot themselves in the foot with.
* I don't see raw script as a user friendly solution for additional meta data for the same reason I don't think letting users enter raw html meta data is a good idea.
* Having it baked in makes it difficult for those who don't want that to remove it completely.

That said it seems reasonable for some use cases with some users but the needs of those users can be met with a content template nuget. If a community member needs that and wants to implement it and share it that would be great. That would be an opt in solution and better than a baked in solution in my opinion.

**Comment by CrispinF** [comment]
Thanks for considering this. I think those points could be debated, as this would be an extension of the existing "Developer Tool" useful only to those who understand its risks and capabilities, but it wouldn't be my _preferred_ way of adding rich metadata to a page so very happy to see better ways emerge instead!
We do need to be able to do "proper" Linked Data, as either RDFa or JSON-LD, and I cannot see that would be possible (for HTML pages) with having an option for "raw" editing. (Page editors could already do inline microdata using the html editor, but I wouldn't be surprised if CKEditor mangles this, and anyway that is much harder and less user-friendly than entering a single block in a raw mode).
For template-driven pages the Linked Data could/should be generated from the templated data, so that page content by definition matches the Linked Data. 
So overall I was just suggesting this as a simple way of permitting rich Linked Data on HTML pages, but appreciate the concerns over building it into the core and would be very happy to see better solutions.
And we'll also think about doing a template for this purpose too, but not sure when we can get onto that.

**Comment by CrispinF** [comment]
@joeaudette the ability to upload would help, but actually it's harder to manage piles of badly named files on a remote server than inline script, and the security/CSP issues remain the same.

I do think there will sometimes be value in being able to add inline raw script, so yes happy to sponsor  2 hours on you making a content template for this.

**Comment by joeaudette** [comment]
Closing this since it is completed.
