### ISSUE TITLE
Content Settings always showing and editing from root site

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe.SimpleContent#366]
Initially I thought it is related to ASP.NET Core 2.2 but later I found that even I reverted back to to 2.1 I still cannot see settings for selected site. Instead it should values from root site "/". When I edited settings I see that root site settngs are edited.
Here is site list:
![image](https://user-images.githubusercontent.com/18220536/49892765-9a79e380-fdfe-11e8-98d5-057ed3b2e4da.png)

Here are settings for one of the sites:
![image](https://user-images.githubusercontent.com/18220536/49892799-b1203a80-fdfe-11e8-993d-2a77d3763aa6.png)

and here is changes:
![image](https://user-images.githubusercontent.com/18220536/49892845-d44aea00-fdfe-11e8-8fa7-6eba70ad90c9.png)

As you can see I edited siteId=0d6074b6-abfd-446c-9368-31c3cc8f61be but settings changes for 9d8238f1-3eaa-4cdf-a662-823c740110b0.

Just in case editing done in ASP.NET Core 2.2 so perhaps there is another problem related to 2.2 but settings shows incorrectly in 2.1 as well.

**Comment by joeaudette** [comment]
make sure the file (in each tenant) has an Id property in the json that is the same as the filename guid.

**Comment by cheverdyukv** [comment]
I did search for string "9d8238f1-3eaa-4cdf-a662-823c740110b0" inside each file in "0d6074b6-abfd-446c-9368-31c3cc8f61be" directory and I couldn't find match. 
But in file
`nodb_storage\projects\0d6074b6-abfd-446c-9368-31c3cc8f61be\projectsettings\0d6074b6-abfd-446c-9368-31c3cc8f61be.json` I can see correct Id and file `nodb_storage\projects\0d6074b6-abfd-446c-9368-31c3cc8f61be\sitesettings\0d6074b6-abfd-446c-9368-31c3cc8f61be.json` has correct Id.

**Comment by joeaudette** [comment]
in the 9d8238f1-3eaa-4cdf-a662-823c740110b0 file if it does not have "Id":"9d8238f1-3eaa-4cdf-a662-823c740110b0", then you should add it.

**Comment by joeaudette** [comment]
In cloudscribe core you can manage child site settings (for cloudscribe core features) from the master site but that does not apply to SimpleContent, that site id in the query string does not make it update the child site content settings. You have to login to the child site to update its settings.

The bug is that the navigation file has this:

    <NavNode key="ContentSettings"
                 controller="ContentSettings"
                 action="Index"
                 text="Content Settings"
                 iconCssClass="fas fa-book"
                 preservedRouteParameters="siteId"
                 componentVisibility="breadcrumbs,childtree,parenttree"
                 authorizationPolicy="AdminPolicy">
          <Children></Children>
        </NavNode>

but it should not have preservedRouteParameters="siteId" because that makes you see the siteid in the url and makes you think it works the same as cloudscribe core. It does not work the same it is only managed from within the same site.
I will remove that from the template.

**Comment by cheverdyukv** [comment]
Ok that explains it. Thank you!
