### ISSUE TITLE
Perf: Files that returned via /csscsr do not have ETag on them

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe.SimpleContent#368]
It is not a bug, just small performance issue. There are two "files":
`/csscsr/css/blog-common.min.css`
`/csscsr/js/blog-comments.min.js`
that do not have ETag and result they are always downloaded by browser for any post. 
These two "files" are quite small (2.2Kb and 4.92Kb) but still they are two additional requests for resources that never changes once site is deployed.

`/csscsr/css/simple-gallery.min.css` downloaded by browser on list of posts.

**Comment by joeaudette** [comment]
should be fixed in the latest nugets

**Comment by cheverdyukv** [comment]
It is fixed in Firefox and now all queries returns 304 but in Opera that based on Chrome it works different. For all other files there are no requests to server at all. But these two still send request to server:
![image](https://user-images.githubusercontent.com/18220536/50565990-5d13c200-0ce9-11e9-8b78-ef28b424eae0.png)

**Comment by joeaudette** [comment]
I tested in Chrome and it works, I have not tested in opera. I would suggest try clear all browser cache.

**Comment by cheverdyukv** [comment]
So in Chrome there are no requests at all and everything from memory cache?

**Comment by joeaudette** [comment]
Those other files come from either static resources or from local static resources. I didn't change anything about how those files are handled. 

The ones you mentioned before come from controller actions that serve embedded resources and those are the only ones I made changes for. Static resources seem to already work correctly on my machine using FF or Chrome.

**Comment by cheverdyukv** [comment]
My question was why browser didn't cache items that "come from controller actions that serve embedded resources"? For browser there should be no difference.

**Comment by joeaudette** [comment]
In Chrome on empty cache the first request is 200, then subsequent requests get 304 when the browser passes the IfNoneMatch header with the previous etag it cached. If the current etag matches we return 304 otherwise we return the file with 200 response. The whole idea is the 304 is a lighter response and therefore faster.

The difference is apparently static files middleware already adds etag header, my controller actions that are serving embedded files were not setting that header before but now they do.

**Comment by cheverdyukv** [comment]
I know how ETag and IfNoneMatch works. My question was why Chrome didn't send request for query.min.js but still send request for blog-common.min.js? Yes it returns 304 but it is still request. I found that query.min.js set Last-Modified header but blog-common.min.js does not. Maybe problem there?
Just in case it is minor problem and 304 already great result.

**Comment by joeaudette** [comment]
The browser will only send IfNoneMatch header if it already requested it before and there was an etag header returned in the response, if there was no etag header the last time the browser requested the file then it can't send the IfNoneMatch header in the request, it can only send that header if it has an etag to check and it passes the etag back to the server in that header.

Maybe static files middleware works different, and uses only last modified header not etag, in any case static files seem to work fine for me getting 304 on subsequent requests perhaps due to last modified header instead of etag header.
