### ISSUE TITLE
Template for list of links doesn't work for internal links

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#370]
This content template "A list of links with optional thumbnail per link and content above and below" requires fully qualified links, and won't accept internal links, plus it always creates target="_blank" links.
I have a user who really wants to use this template to organise links to other pages with the same site.  
It would be nice if the validation could accept internal links, and if the decision to open in same or new tab could be made per added link (OR make internal links open in same tab, external in new).

**Comment by joeaudette** [comment]
The target attribute could be removed by overriding the [render view](https://github.com/cloudscribe/cloudscribe.SimpleContent/blob/master/src/cloudscribe.SimpleContent.ContentTemplates.Bootstrap4/Views/Shared/ContentTemplates/ListOfLinksRender.cshtml) in your project.

The relative url issue seems to be because we are using the intput type=url in order to validate the entered url and then using its built in validation like this:

     var _testEle = document.createElement('input');
     _testEle.setAttribute('type', 'url');
     var isValid = _testEle.validity.valid;

and that input type does not allow relative urls.

So to fix that we will have to re-consider how to validate.

**Comment by joeaudette** [comment]
We can easily add a config option for whether to use target or maybe a per url setting so unless you need it right away I would hold off on overriding the view.

**Comment by CrispinF** [comment]
Thanks  @joeaudette It's an active build aiming to go live within a couple of weeks. Do you have a change in mind to improve this?  Happy to sponsor a little time if needed, though our budget on this project is miniscule.

**Comment by joeaudette** [comment]
@CrispinF I'm guessing 1 hour or less to solve this, if you're good with that I can definitely expedite this.

I'm thinking a new property for each link for "Opens in new window?".

For validation I'm thinking of something pretty liberal, ie it starts with / or it validates as before. The way the rendering works for content templates I don't see any security issue for invalid input so the worst case I think is broken links and that seems reasonable for bad input.

**Comment by CrispinF** [comment]
@joeaudette please go ahead, thanks.

**Comment by joeaudette** [comment]
This is now completed and an updated nuget is available.

**Comment by CrispinF** [comment]
@joeaudette will any existing pages that used this template need to be deleted and re-created?

**Comment by joeaudette** [comment]
No, just re-saved in order to re-render.
