### ISSUE TITLE
Allow dynamic content in Content Templates

### ISSUE THREAD

**Issue by evilGitHub** [cloudscribe/cloudscribe.SimpleContent#373]
It would be nice to have a way to either mark a Content Template Page to be rendered on each request to make it possible to use dynamic c#/razor code in template, or to mark a portion of that page to rendered on each request.

**Comment by joeaudette** [comment]
I think I can add a setting for templates to indicate if they should render dynamically. It will be an either/or thing, no option for partial rendering of the template.

I think in all cases on save we will still render a string into the main content body. But if the template is designed to render every time, then inside the view we can detect that and deserialize the saved template model and pass it into the render view, instead of just rendering the already saved string from the main content body.

**Comment by joeaudette** [comment]
Actually just thought of a problem though. The render view for a template is not a partial view, it is a main view that uses an empty layout, so it can't be used as a partial view.

It isn't a huge problem though, I will just have to use another new property for a RenderPartialView and that will have to be provided for templates designed to render dynamically in addition to a main render view. The main render view will still be required since I still think we should always render into the content body on save, but it could internally use the partial render view so there would be no duplication.

**Comment by joeaudette** [comment]
This is now completed, updated nugets have been published and I have updated the documentation to explain about how to use dynamic rendering.
https://www.cloudscribe.com/docs/content-templates
