### ISSUE TITLE
URL override oddity, and how to break the sitemap

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#396]
Wanted a link to /sitemap in top menu, so created a page with a URL override "sitemap".  This worked fine, but I noticed an oddity.  As soon as we click Save, i.e. when we are still looking at the editing form for the new page, OR when we are in edit mode on any _other_ page, e.g. /editpage/home then the menu item "Site Map" is actually pointing to https://mysite.com/editpage/sitemap

And if we click it, we arrive on a form for creating a new page with a slug of "sitemap", which is _really_ confusing!

I resolved to bring this to your attention. But then I just wondered whether setting the URL override to "/sitemap" might help.  So I did this in the page settings:
![image](https://user-images.githubusercontent.com/10574730/52806419-e48e7800-3080-11e9-8fed-9e130196362a.png)

Oh no! It's happy to save that, but now the menu link opens an empty page with the correct URL but no content, i.e. my sitemap is bust.

**Comment by joeaudette** [comment]
this is fixed in the latest nugets. technically when entering relative urls you should use /sitemap not sitemap but sitemap passes the regex for an external or relative url so it is allowed, it just does not get resolved correctly. To fix it in the page tree builder, if the provided override doesn't start with http or / I prepend it with / to solve the problem.

But then the sitemap page didn't really work because the navigation component now had a non null current node for sitemap and was trying to show its children. whereas when current node is null starting node or root node is resolved as current node. So I had to modify the sitemap view in the navigation library as well.
