### ISSUE TITLE
Blog "Publish Later" for dates in the past

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#422]
There's a legitimate need for publishing posts at dates in the past.   One is when transferring posts from another site/blog, to ensure ordering and archive tags are valid.
The cloudscribe blog offers the capability to set the publishing date, but assumes the dates will be in the future:
![image](https://user-images.githubusercontent.com/10574730/54498675-0db15b00-4902-11e9-824d-5e2d8ce34e6a.png)
and after this we see:
![image](https://user-images.githubusercontent.com/10574730/54498684-228dee80-4902-11e9-9025-689cd6e59069.png)
Note: at this moment, the post is not visible to anyone else. If I visit the URL in a different browser I get a "Page not found". Also, strangely, at this moment the archive tags show incorrect presence and count from the current month-year (i.e. 2019-03). I have two other blogs in the site - is it getting archive tags and counts from them at this moment? 
![image](https://user-images.githubusercontent.com/10574730/54498899-5702aa00-4904-11e9-94c3-4e4a0f4b895d.png)
If I then navigate to the root of the blog, things correct themselves: the post becomes visible to other sessions and the bad archive tag disappears.
![image](https://user-images.githubusercontent.com/10574730/54498924-81546780-4904-11e9-9ba6-9709574763d2.png)

Could the workflow perhaps be slightly different when a post is saved with a publish date in the past, and might the button label perhaps be changed to "Publish at Date/Time:" instead of "Publish Later:"?
And as noted above there may be a small bug in the archives tags in this scenario.

**Comment by joeaudette** [comment]
Thanks for the excellent feedback. This should now be fixed in the latest nugets. Now if the provided date is in the past we go ahead and publish. What was happening before was that the post was not marked as published because the button command is publish later. But unpublished posts that are due for publishing are auto published when visiting the post list. I've updated it so that if the provided date is in the past we go ahead and mark it as published. I've updated the button label as suggested as well.
