### ISSUE TITLE
Suggested blog URL feature and slug edit ability for blog posts created from new templates

### ISSUE THREAD

**Issue by hsankala** [cloudscribe/cloudscribe.SimpleContent#432]
Hi Joe, you've probably already considered this, but I'll raise it just in case it gives some new information on the subject.

I was reading this article: [https://www.hanselman.com/blog/URLsAreUI.aspx](https://www.hanselman.com/blog/URLsAreUI.aspx).  And it talks about a blended approach to a url structure a sort of static/dynamic hybrid, that might be worth considering for the CS simple content module.

The basic premise is that you have a unique ID (static) baked into the URL the e.g like stackoverflow 
 https://stackoverflow.com/questions/701030/whats-the-significance-of-oct-12-1999 
so the `701030` is the static id, what comes after it is just for the humans and SEO and could potentially be updated when the page title (slug) is changed. 

Thought this might be a good feature for blog posts where SEO is more emphasized.  

#334 Granted the ability to edit slugs for blog posts created with the standard content editor, unfortunately this does not carry over to posts created from any of the new templates, it would be good to have this facility throughout.

**Comment by joeaudette** [comment]
@hsankala I think we already have good seo with simplecontent urls. We don't have any query string params for posts and pages so we don't need some special code segment to shorten that. We only have the slug which is generated from the title.

Most non-technical users should never really have to think about the slug, and in general best to avoid changing the slug after a page or post has been created because that would hurt seo.

For more technical folks who do want to edit the slug and understand the implications of doing so, you just need to override the views [EditSlugPartial](https://github.com/cloudscribe/cloudscribe.SimpleContent/blob/master/src/cloudscribe.SimpleContent.CompiledViews.Bootstrap4/Views/Blog/EditSlugPartial.cshtml) and [EditWithTemplateSlugPartial](https://github.com/cloudscribe/cloudscribe.SimpleContent/blob/master/src/cloudscribe.SimpleContent.CompiledViews.Bootstrap4/Views/Blog/EditWithTemplateSlugPartial.cshtml) to change from a hidden input to a visible input for the slug to be editable.

A solution like hanselman is talking about may be useful for getting rid of query string params by shortening them into one code but it also makes seo more complicated because it allows any extra stuff in the url and if more than one url returns the same content that is bad for seo and then you need to [specify a canonical url](https://support.google.com/webmasters/answer/139066?hl=en) which is not needed when there is only one url for the content.

**Comment by hsankala** [comment]
I see what your saying.

Oh I didn't know about `EditWithTemplateSlugPartial` is already there. Great cheers
