### ISSUE TITLE
Image gallery template: add optional alt text and hyperlink properties. Also ensure descr is shown in all layouts.

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#470]
Often the description is not appropriate alt text for an image. Also, we may want the image title to be a hyperlink to some other page. This should work in all layout options.
Also noticed that the Description is not visible in full-width carousel... entered properties should be visible in all layouts.

**Comment by JimKerslake** [comment]
Seems achievable, though not as simple as I initially thought... will need to include some consideration of the other shipped templates too.

Easy enough to add extra fields to the edit and the render views for this one template, but...
there is also a bunch of Knockout.js code to manage the image handling... which is factored to deal with the common aspects of "list item" management across all 8 of the shipped content templates... so changes to implement this ticket (in that JS) might potentially have some effect upon other templates too.

Also need to be cautious that existing pages store a 'SerializedModel' field with a JSON serialization of the current viewmodel… so will pages made with the old version of the template have problems on migration to the newer version, since their JSON model will be lacking the new properties expected in the template editor... that needs testing.

**Comment by JimKerslake** [comment]
I have an implementation of this that works for me... subject to more testing of the two issues in previous comment.  (watch for js console errors.)  

Feature/470 branch  - I did not PR this yet.

Actually the only other template that shares the same knockout script seems to be the 'Everything' template (which I think is probably the same as 'flexible complex')

**Comment by JimKerslake** [comment]
Also removed carousel-fade class from the carousel (request of Stewart B)

**Comment by JimKerslake** [comment]
I think I can just bump the version of  cloudscribe.SimpleContent.ContentTemplates.Bootstrap4  since the VSIX has a direct dependency on it.   (Tested that locally.)

Tested that old pages using the same template survive the upgrade.  
(Limited testing that other templates seem to be unaltered.)

**Comment by JimKerslake** [comment]
This was pushed to nuget.org as v3.0.2 of  cloudscribe.SimpleContent.ContentTemplates.Bootstrap4 
(but as per the comment above, that's all that was required).
https://www.nuget.org/packages/cloudscribe.SimpleContent.ContentTemplates.Bootstrap4/3.0.2

There is no BS3 equivalent project, so ticket can be closed once satisfied that it's been sufficiently tested.
