### ISSUE TITLE
Import from Rss, Teaser Service Issue

### ISSUE THREAD

**Issue by abomadi** [cloudscribe/cloudscribe.SimpleContent#481]
I have tried to import bulk of articles and then published them manually, however i keep receiving this error 
_produced invalid html, so trying again and increasing the truncation length to 40 words. You should re-publish this post to create a persistent teaser._
any idea what is the cause ?, also i have noticed there is a slowness when opening articles pages is this related to cache ?

**Comment by joeaudette** [comment]
creating a teaser is an expensive and error prone process which is why we do it at save time rather than render time. 
Are you sure that is being logged as an error? I think it is probably warning.
What happens is that by some rule the html gets truncated to create the teaser but we check the truncated fragment for validity and if it is not a valid fragment (ie missing close tag etc) we increase the characters to truncate until it is valid which can take many loops making it an expensive process.

Doing that in bulk is probably not a good idea, but if it is only a warning and not an error then maybe you can get away with it. It was really designed to only happen when a user edits the content.

Also by default teasers are not enabled, you could disable it, then do bulk import, then go through each one click edit then save to generate the teasers.

**Comment by abomadi** [comment]
@joeaudette actually its a warning, also when i imported the posts the teaser was off, after enabling it i got flooded with this warning

```
warn: cloudscribe.SimpleContent.Web.Services.TeaserService[0]
cloudscribe.SimpleContent.Web.Services.TeaserService: Warning: teaser truncation for post post-title-name, produced invalid html, so trying again and increasing the truncation length to 109 words. You should re-publish this post to create a persistent teaser
```
Also i have noticed the following strange behavior :
- After importing the post directly turning on the teaser, the posts in /article list page brings them truncated but when i edit the post and publish it again the teaser wont work! however the strange thing that if i change the theme to custom-1 for example the teaser works but also with the same warning messages
- im afraid the teaser is consuming the connections to database, if you are deploying to cloud ready sql servers you have a max connection limit, and im facing this issue all the time not sure if its from the teaser or the logging (log is on different db but same server)
- another issue im not able to see the uploaded image for the post on the article list page, after tracking the code it seems this was the required behavior when parsing the html, any idea how to bring it there
